name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: quill-task-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: quill-task-aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: quill-task-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: quill-task-x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: quill-task-x86_64-pc-windows-msvc.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install musl tools (Linux musl only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/quill-task release/${{ matrix.asset_name }}
          chmod +x release/${{ matrix.asset_name }}

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          copy target\${{ matrix.target }}\release\quill-task.exe release\${{ matrix.asset_name }}

      - name: Create tarball (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd release
          tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}

      - name: Create zip (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd release
          7z a ${{ matrix.asset_name }}.zip ${{ matrix.asset_name }}

      - name: Upload Release Asset (Unix)
        if: matrix.os != 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/${{ matrix.asset_name }}.tar.gz

      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/${{ matrix.asset_name }}.zip

  update-homebrew:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula@v3
        with:
          formula-name: quill-task
          formula-path: Formula/quill-task.rb
          homebrew-tap: MatthewMyrick/homebrew-quill
          download-url: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/quill-task-x86_64-apple-darwin.tar.gz
          commit-message: |
            Update quill-task to ${{ steps.extract_version.outputs.VERSION }}
            
            Created by release workflow
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}