name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-upload:
    environment: production
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: quill-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: quill-aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: quill-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: quill-x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: quill-x86_64-pc-windows-msvc.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release binary
        uses: ./.github/actions/build.yml
        with:
          target: ${{ matrix.target }}
          release: true
          run-tests: false

      - name: Prepare binary
        run: |
          mkdir -p release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/quill.exe release/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/quill release/${{ matrix.asset_name }}
            chmod +x release/${{ matrix.asset_name }}
          fi

      - name: Create archive
        run: |
          cd release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ${{ matrix.asset_name }}.zip ${{ matrix.asset_name }}
          else
            tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/${{ matrix.asset_name }}.*
