name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-upload:
    environment: production
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: quill-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: quill-aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: quill-x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: quill-x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: quill-x86_64-pc-windows-msvc.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install openssl pkg-config
            if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
              # Install Intel Homebrew if it doesn't exist
              if [ ! -f /usr/local/bin/brew ]; then
                echo "Installing Intel Homebrew..."
                arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              fi
              # Install x86_64 OpenSSL for Intel builds
              arch -x86_64 /usr/local/bin/brew install openssl pkg-config
              OPENSSL_PATH=$(arch -x86_64 /usr/local/bin/brew --prefix openssl)
              echo "OPENSSL_ROOT_DIR=$OPENSSL_PATH" >> $GITHUB_ENV
            else
              # Use ARM64 OpenSSL for Apple Silicon builds
              echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
            fi
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y pkg-config libssl-dev
            if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then
              sudo apt-get install -y musl-tools
            fi
          fi

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          # Set OpenSSL paths for macOS
          OPENSSL_DIR: ${{ env.OPENSSL_ROOT_DIR }}
          PKG_CONFIG_PATH: ${{ format('{0}/lib/pkgconfig', env.OPENSSL_ROOT_DIR) }}
          PKG_CONFIG_ALLOW_CROSS: ${{ matrix.target == 'x86_64-apple-darwin' && '1' || '' }}
          # Set macOS deployment target to match runner version
          MACOSX_DEPLOYMENT_TARGET: "14.0"

      - name: Prepare binary
        run: |
          mkdir -p release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/quill.exe release/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/quill release/${{ matrix.asset_name }}
            chmod +x release/${{ matrix.asset_name }}
          fi

      - name: Create archive
        run: |
          cd release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ${{ matrix.asset_name }}.zip ${{ matrix.asset_name }}
          else
            tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/${{ matrix.asset_name }}.*
