name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: quill-task-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: quill-task-aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install OpenSSL (macOS)
        run: |
          brew install openssl pkg-config
          if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
            # Install Intel Homebrew if it doesn't exist
            if [ ! -f /usr/local/bin/brew ]; then
              echo "Installing Intel Homebrew..."
              arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
            # Install x86_64 OpenSSL for Intel builds
            arch -x86_64 /usr/local/bin/brew install openssl pkg-config
            OPENSSL_PATH=$(arch -x86_64 /usr/local/bin/brew --prefix openssl)
            echo "OPENSSL_ROOT_DIR=$OPENSSL_PATH" >> $GITHUB_ENV
          else
            # Use ARM64 OpenSSL for Apple Silicon builds
            echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
          fi

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          # Set OpenSSL paths for macOS
          OPENSSL_DIR: ${{ env.OPENSSL_ROOT_DIR }}
          PKG_CONFIG_PATH: ${{ format('{0}/lib/pkgconfig', env.OPENSSL_ROOT_DIR) }}
          PKG_CONFIG_ALLOW_CROSS: ${{ matrix.target == 'x86_64-apple-darwin' && '1' || '' }}
          # Set macOS deployment target to match runner version
          MACOSX_DEPLOYMENT_TARGET: "14.0"

      - name: Prepare binary
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/quill release/${{ matrix.asset_name }}
          chmod +x release/${{ matrix.asset_name }}

      - name: Create tarball
        run: |
          cd release
          tar -czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/${{ matrix.asset_name }}.tar.gz

  update-homebrew:
    needs: build-and-upload
    runs-on: macos-latest
    steps:
      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula@v3
        with:
          formula-name: quill-task
          formula-path: Formula/quill-task.rb
          homebrew-tap: MatthewMyrick/homebrew-quill
          download-url: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/quill-task-x86_64-apple-darwin.tar.gz
          commit-message: |
            Update quill-task to ${{ steps.extract_version.outputs.VERSION }}

            Created by release workflow
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
